### ISSUE TITLE
RFE: use source of basic images like virt-deploy project

### ISSUE THREAD

**Issue by jscotka** [avocado-framework/avocado-virt#33]
Hi,
as we discussed, there is now only one prepared  image + customization part.
It would be clean, to use it in similar way how uses virt-deploy project:
https://github.com/simon3z/virt-deploy
It is downloading base images from http://libguestfs.org/
so that you don't need to do same thing. 
    Regards
    Honza

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Library of VM images definitions](https://trello.com/c/zOok8ytO/15-library-of-vm-images-definitions)

**Comment by ldoktor** [comment]
Thank you, @jscotka, let's track this in trello: https://trello.com/c/zOok8ytO/15-library-of-vm-images-definitions

**Comment by jscotka** [comment]
Hi @ldoktor, thanks for implementing that. It is too old issue that I've forgot that I've ever filed that :-)
 Perfect, thanks

**Comment by ldoktor** [comment]
It's not implemented, I closed it because there is a trello card to work on this which is our primary tracing and scheduling tool. Right now it's not really a priority, but contributions are always welcome 😉
