### ISSUE TITLE
graceful vm.power_off()

### ISSUE THREAD

**Issue by apahim** [avocado-framework/avocado-virt#86]
Currently we power of the VM with the qemu monitor command `quit`:
https://github.com/avocado-framework/avocado-virt/blob/master/avocado_virt/qemu/machine.py#L144

Let's be nice, trying first to push the power button:
https://en.wikibooks.org/wiki/QEMU/Monitor#system_powerdown

And use `quit` only is the `system_powerdown` does not work.

**Comment by ldoktor** [comment]
Actually IIRC `system_powerdown` only works with GA installed, right? If so then I'd prefer using the `avocado-vt` method, which uses `ssh` connection and sends the shutdown command (`virttest.qemu_vm.VM.graceful_shutdown`)

**Comment by apahim** [comment]
@ldoktor nope, `system_powerdown` does not depend on `qemu-ga`. It's an ACPI signal. I'd prefer not depending on ssh to poweroff a vm.

**Comment by ldoktor** [comment]
OK, cool. I just remember the `shutdown` button does not work on my manually created machines in `virt-manager`.

**Comment by famz** [comment]
Why? The test can handle shutdown gracefully if it's desired. Waiting for the guest to shutdown is a waste of time otherwise.

**Comment by ldoktor** [comment]
Well the idea is that there should be an option `vm.power_off(gracefully=False)`. Then the test could simply decide whether it needs the machine to be destroyed immediately, or rather wait for it to finish.

**Comment by ldoktor** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [avocado-virt: Add support to gracefully shutdown the VM](https://trello.com/c/X5iH9DEs/1012-avocado-virt-add-support-to-gracefully-shutdown-the-vm)

**Comment by ldoktor** [comment]
Let's track this card in trello: https://trello.com/c/X5iH9DEs/1012-avocado-virt-add-support-to-gracefully-shutdown-the-vm
